name: Build Application

on: 
  push:
    branches:
      - main

env:
   ENVIRONMENT: development


jobs:
    build:
        runs-on: windows-latest
        environment: development

        steps:

          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: ${{ vars.DOTNET_VERSION }}

          - name: Restore Dependencies
            run: dotnet restore

          - name: Build API
            run: dotnet build github-actions-demo\github-actions-demo.csproj --no-restore